name: Generate Pacman Contribution Graph

permissions:
  contents: write
  
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Pacman Contribution Graph

    steps:
      - uses: actions/checkout@v3

      - uses: abozanona/pacman-contribution-graph@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pacman.svg
          git commit -m "Generate Pacman contribution graph"
          git push
